import React from 'react';
import { X, FileText, ShieldCheck, Download } from 'lucide-react';
import type { ReportItem } from '../types';

interface ReportDrawerProps {
  report: ReportItem | null;
  onClose: () => void;
  onDownload: (name: string) => void;
}

export const ReportDrawer: React.FC<ReportDrawerProps> = ({
  report,
  onClose,
  onDownload,
}) => {
  if (!report) return null;

  return (
    <div className="drawer-backdrop" onClick={onClose}>
      <div className="drawer-slide-content" onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
          <span style={{ fontSize: '0.72rem', fontWeight: 800, color: '#7c3aed', background: '#f5f3ff', padding: '4px 10px', borderRadius: '6px', textTransform: 'uppercase' }}>
            {report.category} Scope
          </span>
          <button 
            onClick={onClose}
            style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', outline: 'none' }}
          >
            <X size={20} />
          </button>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px' }}>
          <div style={{ background: '#f5f3ff', padding: '10px', borderRadius: '12px', color: '#7c3aed' }}>
            <FileText size={22} />
          </div>
          <div>
            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>{report.name}</h2>
            <div style={{ fontSize: '0.76rem', color: 'var(--text-secondary)', fontWeight: 500, marginTop: '2px' }}>
              Audited Class: {report.category} • Size: {report.fileSize}
            </div>
          </div>
        </div>

        <div style={{ height: '1px', background: '#f1f5f9', margin: '18px 0' }}></div>

        <h3 style={{ fontSize: '0.76rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.04em', fontWeight: 700, marginBottom: '8px' }}>
          Report summary
        </h3>
        <p style={{ fontSize: '0.84rem', color: 'var(--text-primary)', fontWeight: 500, lineHeight: 1.5, marginBottom: '20px' }}>
          {report.description}
        </p>

        <div style={{ background: '#f8fafc', padding: '14px', borderRadius: '12px', border: '1.5px solid #f1f5f9', display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
          <div>
            <div style={{ fontSize: '0.68rem', color: 'var(--text-secondary)', fontWeight: 700, textTransform: 'uppercase' }}>GENERATED BY</div>
            <div style={{ fontSize: '0.84rem', fontWeight: 650, color: 'var(--text-primary)', marginTop: '3px' }}>{report.generatedBy}</div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: '0.68rem', color: 'var(--text-secondary)', fontWeight: 700, textTransform: 'uppercase' }}>DATE GENERATED</div>
            <div style={{ fontSize: '0.84rem', fontWeight: 650, color: 'var(--text-primary)', marginTop: '3px' }}>{report.dateGenerated}</div>
          </div>
        </div>

        <div style={{ background: '#ecfdf5', padding: '14px', borderRadius: '12px', border: '1px solid #d1fae5', display: 'flex', gap: '8px', marginBottom: '20px' }}>
          <ShieldCheck size={18} color="#059669" style={{ flexShrink: 0 }} />
          <div>
            <div style={{ fontSize: '0.76rem', color: '#065f46', fontWeight: 700, textTransform: 'uppercase' }}>Audited & Verified</div>
            <p style={{ fontSize: '0.78rem', color: '#047857', fontWeight: 550, margin: '3px 0 0 0', lineHeight: 1.4 }}>Matches standard local accounting protocols and tax audits.</p>
          </div>
        </div>

        <button 
          onClick={() => onDownload(report.name)}
          style={{
            marginTop: 'auto', width: '100%', padding: '12px', borderRadius: '12px', border: 'none',
            background: 'var(--primary-glow)', color: '#ffffff',
            fontWeight: 700, fontSize: '0.85rem', cursor: 'pointer', outline: 'none',
            boxShadow: '0 4px 12px rgba(124, 58, 237, 0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px'
          }}
        >
          <Download size={16} /> Export File
        </button>
      </div>
    </div>
  );
};
